### PR TITLE
fix: list, flashlist, sectionlist v2

### LINKED ISSUE #102: List Component V2 - rendering problems (flashlist&sectionlist)
We encountered rendering problem with the List component and not with the FlatList from React Native which should behave the same.
To fix this issue, it seems that we only need to move the declaration of the const FicusFlatList outside of the List function so that it does not creates a new one at each call as follows : 
```
import React from 'react';

import {
  FlatList as RNFlatList,
  FlatListProps as RNFlatListProps,
} from 'react-native';

import { NativeFicusProps, ficus } from '../system';

type ListProps<ItemT> = RNFlatListProps<ItemT> &
  Omit<NativeFicusProps<'FlatList'>, keyof RNFlatListProps<ItemT>>;

const FicusFlatList = ficus(RNFlatList, {
  baseStyle: { flex: 1 },
}) as React.ComponentType<any>;

export function List<ItemT>(props: ListProps<ItemT>) {
  return <FicusFlatList {...props} />;
}

```

According to the ficus code base, the same problem and solution should apply for the section list and the flashlist

### PR DESCRIPTION
**Pull request by heloise-gllm**
Closes #102 

Tested locally for the List component

### CODE REVIEW

File: packages/react-native-ficus-ui/src/components/list/index.tsx [hunk 1]
```diff
@@ -10,9 +10,10 @@ import { NativeFicusProps, ficus } from '../system';
 type ListProps<ItemT> = RNFlatListProps<ItemT> &
   Omit<NativeFicusProps<'FlatList'>, keyof RNFlatListProps<ItemT>>;
 
+const FicusFlatList = ficus(RNFlatList, {
+  baseStyle: { flex: 1 },
+}) as React.ComponentType<any>;
+
```
Comment (omar-bear) [inline packages/react-native-ficus-ui/src/components/list/index.tsx:16]: I think we have to do that for all components

File: packages/react-native-ficus-ui/src/components/flash-list/index.tsx [hunk 2]
```diff
@@ -8,9 +8,10 @@ import { NativeFicusProps, ficus } from '../system';
 type FlashListProps<ItemT> = RNFlashListProps<ItemT> &
   Omit<NativeFicusProps<'FlashList'>, keyof RNFlashListProps<ItemT>>;
 
+const FicusFlatList = ficus(RNFlashList, {
```
Comment (heloise-gllm) [inline packages/react-native-ficus-ui/src/components/flash-list/index.tsx:11]: should be flashlist and not flatList
